### ISSUE TITLE
When I execute a get command on the SupplyChain app frontend to  get the suppliers detail , then the application returns a error as follow 

### ISSUE THREAD

**Issue by elohffa** [xcottos/convector-example-supplychain-master#2]
(node:5259) UnhandledPromiseRejectionWarning: Error: Transaction proposal was bad
supplychain-app:     at FabricControllerAdapter.<anonymous> (/home/suntaiwai/convector-example-supplychain-master/packages/supplychain-app/node_modules/@worldsibu/convector-common-fabric-helper/src/client.helper.ts:294:19)
supplychain-app:     at step (/home/suntaiwai/convector-example-supplychain-master/packages/supplychain-app/node_modules/tslib/tslib.js:133:27)
supplychain-app:     at Object.next (/home/suntaiwai/convector-example-supplychain-master/packages/supplychain-app/node_modules/tslib/tslib.js:114:57)
supplychain-app:     at fulfilled (/home/suntaiwai/convector-example-supplychain-master/packages/supplychain-app/node_modules/tslib/tslib.js:104:62)
supplychain-app:     at <anonymous>
supplychain-app: (node:5259) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)

**Comment by elohffa** [comment]
Final I fixed  .
